### ISSUE TITLE
groupadd: GID '497' already exists

### ISSUE THREAD

**Issue by cardguy1000** [tkimball83/plexconnect#1]
When trying to run "rpm -ivh plexconnect-20150412-1.el6.noarch.rpm' I would get the following error:
groupadd: GID '497' already exists

I ended up checking /etc/group for a free groupid and then modifying rpmbuild/SPECS/plexconnect.spec to use 503 (my free groupid) instead of 497.  Perhaps the spec can be modified to find a free groupid somehow

%pre
getent group %{name} >/dev/null || groupadd -g 503 -r %{name}
getent passwd %{name} >/dev/null || \
  useradd -r -u 503 -g %{name} -s /sbin/nologin \
    -d %{_localstatedir}/lib/%{name} -c "RPM Created PlexConnectUser" %{name}

**Comment by tkimball83** [comment]
This has been fixed in commit 98753db0e4a60ba2d40eb121934651ae5a4a34ac.

When you have a moment, please confirm that all is well on your end.  Thanks!
