### ISSUE TITLE
Run as root

### ISSUE THREAD

**Issue by box25** [tkimball83/plexconnect#2]
Not sure if it is my setup, but running centos 7, I had to change the the user and group to root, in the service config file, otherwise plexconnect would not start as it was unable to bind to port 80

**Comment by tkimball83** [comment]
If you're going to use this package you'll need to pick a port greater than 1024 for plexconnect.  In the example settings.cfg it's using port 8080 so you don't have to run it as root, but you can pick any port number you'd like.

Your web server (apache or nginx) will service the requests on port 80 and then proxy them back to plexconnect which lives on port 8080.

Are you using apache or nginx to service the incoming requests?
